*       *********************************************************
*       *                                                         
*       * 24/05/2007            WINDOW.MPR              13:41:21  
*       *                                                         
*       *********************************************************
*       *                                                         
*       * Author's Name                                           
*       *                                                         
*       * Copyright (C) 2007 Company Name                         
*       * Address                                                 
*       * City,     Zip                                           
*       *                                                         
*       * Description:                                            
*       * This PROGRAM was automatically generated BY GENMENU.    
*       *                                                         
*       *********************************************************


*       *********************************************************
*       *                                                         
*       *                        Setup Code                       
*       *                                                         
*       *********************************************************
*

*       *********************************************************
*       *                                                         
*       *                      Menu Definition                    
*       *                                                         
*       *********************************************************
*


DEFINE PAD Window OF _MSYSMENU PROMPT "\<Ventana" COLOR SCHEME 3 ;
	AFTER _MFILE ;
	KEY ALT+V, "ALT+V" ;
	MESSAGE "Selección de ventana"
ON PAD Window OF _MSYSMENU ACTIVATE POPUP window

DEFINE POPUP window MARGIN RELATIVE SHADOW COLOR SCHEME 4
DEFINE BAR 1 OF window PROMPT "Se eliminará esta barra"

ON SELECTION MENU _MSYSMENU *-- (c) Microsoft Corporation 1995

*       *********************************************************
*       *                                                         
*       *                 Cleanup Code & Procedures               
*       *                                                         
*       *********************************************************
*

RELEASE BAR 1 OF Window
