#IFNDEF _ERR
    #define _ERR
    #IFNDEF CR
        #define CR chr( 13 )
    #ENDIF
	#define ERR1 'File "name" does not exist.' + CR + 'The file specified does not exist.'
	#define ERR3 'File is in use.' + CR + 'You have attempted a USE, DELETE, or RENAME command on a file that is currently open.'
	#define ERR4 'End of file encountered.' + CR + 'The record pointer was positioned past the last record in the file.'
	#define ERR5 'Record is out of range.' + CR + 'The record number you attempted to access is beyond the actual number of records contained in the current table.' + CR + 'The current index does not match the table' + CR + 'Issue REINDEX on the table to try and correct the problem.'
	#define ERR6 'Too many files open.' + CR + 'Visual FoxPro has attempted to open more than its internal limit of files.'
	#define ERR7 'File already exists.' + CR + 'The file name you have attempted to rename already exists. This error is usually generated by the RENAME command.'
	#define ERR9 'Data type mismatch.' + CR + 'An expression is invalid because it is composed of data types that Visual FoxPro cannot evaluate together.' + CR + 'You have either specified an inappropriate data type, or the two fields specified in an operation between two tables (such as UPDATE, REPLACE, SET RELATION) did not have the same data type.'
	#define ERR10 'Syntax error.' + CR + 'You have issued a command that is syntactically incorrect.' + CR + 'You might have misspelled the command or variable name, or used a clause that is not valid in the current context.' + CR + 'Press F1 to see context-sensitive help on the command.'
	#define ERR11 'Function argument value, type, or count is invalid.' + CR + 'A value passed to a function is not of the expected data type, or the value of the argument is out of range for this function, or you are passing too many arguments to a function.'
	#define ERR12 'Variable "variable" is not found.' + CR + 'The specified variable or field name could not be found.'
	#define ERR13 'Alias is not found.' + CR + 'You have attempted to specify an alias that has not been defined. There is no such alias currently in use.'
	#define ERR15 'Not a table.' + CR 'The file that Visual FoxPro is attempting to use as a table contains an improper header.'
	#define ERR16 'Unrecognized command verb.' + CR + 'A word used at the beginning of the command line was not a valid Visual FoxPro command. For more information, see Reserved Words.'
	#define ERR17 'Table number is invalid.' + CR + 'Select a table number between 1 and 225.'
	#define ERR18 'Line is too long.' + CR + 'The maximum length for a command line (8,192 bytes) has been exceeded.' + CR + 'Macro substitution might have caused the line to expand beyond the 8,192-byte limit.'
	#define ERR19 'Index file does not match table.' + CR + 'The index expression for the current index uses variables that are not contained within the current table.'
	#define ERR20 'Record is not in index.' + CR + 'A key field of the table in use has been modified without the index having been active.' + CR + 'Apply the REINDEX command to the table file.'
	#define ERR21 'Length of variable strings exceeds amount of memory.' + CR + 'The combined length of all variable strings has exceeded the amount of memory.'
	#define ERR22 'Too many variables.' + CR + 'The maximum number of variables that can be created has been exceeded. For more information, see Visual FoxPro System Capacities.'
	#define ERR23 'Index expression exceeds maximum length.' + CR + 'The index expression for this index exceeds the maximum length of 220 bytes.'
	#define ERR24 'Alias name is already in use.' + CR + 'You have attempted to use a table with an alias that is associated with another table already in use.'
	#define ERR26 'Table has no index order set.' + CR + 'The records in the table have no order.' + CR + 'An index for the table file was not selected when an UPDATE command using the RANDOM clause was encountered.' + CR + 'Select an index for the table file.' + CR + 'A FIND or SEEK was attempted against a table with no index ordering.' + CR + 'Use SET ORDER TO to specify an index order.' + CR + 'SET RELATION was issued with a non-numeric expression.' + CR + 'Provide a numeric expression.'
	#define ERR27 'Not a numeric expression.' + CR + 'You have attempted to use the SUM command on a non-numeric field.'
	#define ERR30 'Row or column position is off the screen.' + CR
	#define ERR31 'Invalid subscript reference.' + CR
	#define ERR34 'Operation is invalid for a Memo, Blob, General, or Picture field.' + CR
	#define ERR36 'Command contains unrecognized phrase/keyword.' + CR
	#define ERR37 'You must use a logical expression with FILTER.' + CR
	#define ERR38 'Beginning of file encountered.' + CR
	#define ERR39 'Numeric overflow. Data was lost.' + CR
	#define ERR41 'Memo file "name" is missing or is invalid.' + CR
	#define ERR42 'The LOCATE command must be issued before the CONTINUE command.' + CR
	#define ERR43 'There is not enough memory to complete this operation.' + CR
	#define ERR44 'Cyclic relation.' + CR
	#define ERR45 'Not a character expression.' + CR
	#define ERR46 'Expression evaluated to an illegal value.' + CR
	#define ERR47 'No fields found to process.' + CR
	#define ERR50 'Report file "name" is invalid.' + CR
	#define ERR52 'No table is open in the current work area.' + CR
	#define ERR54 'Label file is invalid.' + CR
	#define ERR55 'Memory file is invalid.' + CR
	#define ERR56 'There is not enough disk space for "name".' + CR
	#define ERR58 'LOG( ): Zero or negative used as argument.' + CR
	#define ERR61 'SQRT argument cannot be negative.' + CR
	#define ERR62 'Cannot access characters beyond string.' + CR
	#define ERR67 'Expression evaluator failed.' + CR
	#define ERR78 '** or ^ domain error.' + CR
	#define ERR91 'File was not placed in memory using the LOAD command.' + CR
	#define ERR94 'Must specify additional parameters.' + CR
	#define ERR95 'Statement is not allowed in interactive mode.' + CR
	#define ERR96 'Nesting error.' + CR
	#define ERR101 'Cannot open file "file".' + CR
	#define ERR102 'Cannot create file "file".' + CR
	#define ERR103 'Allowed DO nesting level exceeded.' + CR
	#define ERR104 'Unknown function key.' + CR
	#define ERR107 'Operator/operand type mismatch.' + CR
	#define ERR108 'File is in use by another user.' + CR
	#define ERR109 'Record is in use by another user.' + CR
	#define ERR110 'File must be opened exclusively.' + CR
	#define ERR111 'Cannot update the cursor "cursor", since it is read-only.' + CR
	#define ERR112 'Invalid key length.' + CR
	#define ERR114 'Index does not match the table. Delete the index file and re-create the index.' + CR
	#define ERR115 '.DIF file header is invalid.' + CR
	#define ERR116 '.DIF vector is invalid - .DBF field mismatch.' + CR
	#define ERR117 '.DIF type indicator is invalid.' + CR
	#define ERR119 '.SYLK file header is invalid.' + CR
	#define ERR120 '.SYLK file dimension bounds are invalid.' + CR
	#define ERR121 '.SYLK file format is invalid.' + CR
	#define ERR124 'Printer redirection is invalid.' + CR
	#define ERR125 'Printer is not ready.' + CR
	#define ERR127 'View file is invalid.' + CR
	#define ERR130 'Record is not locked.' + CR
	#define ERR138 'No fields were found to copy.' + CR
	#define ERR152 'Missing expression.' + CR
	#define ERR164 'Menu title has not been defined with DEFINE PAD.' + CR
	#define ERR165 'Menu has not been defined with DEFINE POPUP.' + CR
	#define ERR166 'No menu items have been defined for this menu.' + CR
	#define ERR167 'Menu item position must be a positive number.' + CR
	#define ERR168 'Menu has not been defined with DEFINE MENU.' + CR
	#define ERR169 'Cannot define menu item.' + CR
	#define ERR170 'Cannot release menu item.' + CR
	#define ERR174 'Cannot redefine a menu that is in use.' + CR
	#define ERR175 'Cannot redefine popup that is in use.' + CR
	#define ERR176 'Cannot clear menu that is in use.' + CR
	#define ERR177 'Cannot clear popup that is in use.' + CR
	#define ERR178 'Menu has not been activated with ACTIVATE MENU.' + CR
	#define ERR179 'Menu has not been activated with ACTIVATE POPUP.' + CR
	#define ERR181 'Menu specified in ACTIVATE MENU is already in use.' + CR
	#define ERR182 'Menu specified in ACTIVATE POPUP is already in use.' + CR
	#define ERR202 'Invalid path or file name.' + CR
	#define ERR214 'Window has not been defined with DEFINE WINDOW.' + CR
	#define ERR215 'Window has not been activated with ACTIVATE WINDOW.' + CR
	#define ERR216 'Display mode is not available.' + CR
	#define ERR221 'Left margin including indent must be less than the right margin.' + CR
	#define ERR222 'Line number must be less than page length.' + CR
	#define ERR223 'Column number must be between 0 and 255.' + CR
	#define ERR225 '"name" is not a variable.' + CR
	#define ERR226 '"name" is not a file variable.' + CR
	#define ERR227 'Box dimensions are invalid.' + CR
	#define ERR228 'Tab stops must be in ascending order.' + CR
	#define ERR230 'Array dimensions are invalid.' + CR
	#define ERR231 'Invalid argument used with the SET function.' + CR
	#define ERR232 '"name" is not an array.' + CR
	#define ERR255 'Not a valid RapidFile database.' + CR
	#define ERR256 'Not a valid Framework II database/spreadsheet.' + CR
	#define ERR279 'Menu was not pushed.' + CR
	#define ERR287 'Menu size is too small.' + CR
	#define ERR291 'Expression used with ASIN( ) is out of range.' + CR
	#define ERR292 'Cannot use 0 or negative as the argument for LOG10( ).' + CR
	#define ERR293 'Expression used with ACOS( ) is out of range.' + CR
	#define ERR297 'Lotus 1-2-3 version 2.0 file format is invalid.' + CR
	#define ERR332 'Window specified in DEFINE WINDOW has invalid coordinates.' + CR
	#define ERR350 'Field must be a Memo field.' + CR
	#define ERR355 'Macro is not defined.' + CR
	#define ERR356 'Keyboard macro file format is invalid.' + CR
	#define ERR392 'Maximum record length exceeded in the import file.' + CR
	#define ERR1000 'Internal consistency error.' + CR
	#define ERR1001 'Feature is not available.' + CR
	#define ERR1002 'Input/output operation failure.' + CR
	#define ERR1097 'User defined functions are not allowed.' + CR
	#define ERR1098 'API function _UserError( ) was called.' + CR
	#define ERR1102 'Cannot create file "file".' + CR
	#define ERR1103 'Invalid seek offset.' + CR
	#define ERR1104 'Error reading file "file".' + CR
	#define ERR1105 'Error writing to file "file".' + CR
	#define ERR1106 'Cannot access file "file"; transaction is in progress.' + CR
	#define ERR1108 'Picture too big, corrupt, or in wrong format.' + CR
	#define ERR1111 'Invalid file descriptor.' + CR
	#define ERR1112 'Error closing the file.' + CR
	#define ERR1113 'File is not open.' + CR
	#define ERR1115 'Invalid operation for the cursor.' + CR
	#define ERR1116 'Too many windows open.' + CR
	#define ERR1117 'Key field length does not match.' + CR
	#define ERR1124 'Key exceeds allowed size.' + CR
	#define ERR1126 'Record is too long.' + CR
	#define ERR1127 'You must use a logical expression with a FOR or WHILE clause.' + CR
	#define ERR1130 '"field" phrase is not found.' + CR
	#define ERR1131 'The file specified in the FROM clause is empty.' + CR
	#define ERR1134 'Variable must be in the selected table.' + CR
	#define ERR1138 'Property does not have a default value.' + CR
	#define ERR1140 'FILTER expression exceeds allowed size.' + CR
	#define ERR1141 'Unrecognized index file revision. Re-create the index.' + CR
	#define ERR1145 'Must be a character or numeric key field.' + CR
	#define ERR1147 'Target table is already engaged in a relation.' + CR
	#define ERR1148 'Expression has been re-entered while the filter is executing.' + CR
	#define ERR1149 'Not enough memory for buffer.' + CR
	#define ERR1150 'Not enough memory for file map.' + CR
	#define ERR1151 'Not enough memory for filename.' + CR
	#define ERR1152 'Cannot access the selected table.' + CR
	#define ERR1153 'Cannot rename the file to different device.' + CR
	#define ERR1156 'Duplicate field names.' + CR
	#define ERR1157 'Cannot update the file "file".' + CR
	#define ERR1162 'Procedure "procedure" is not found.' + CR
	#define ERR1163 'Browse table is closed.' + CR
	#define ERR1164 'Browse structure has changed.' + CR
	#define ERR1165 '"field" is not related to the current work area.' + CR
	#define ERR1166 'Cursor is corrupt or in wrong format.' + CR
	#define ERR1167 'Icon is corrupt or in wrong format.' + CR
	#define ERR1168 'Could not add icon to executable file.' + CR
	#define ERR1169 'Project file is read-only.' + CR
	#define ERR1178 'Application file "file" is not closed.' + CR
	#define ERR1181 'Could not add version resource to executable file.' + CR
	#define ERR1183 'Relation already exists.' + CR
	#define ERR1184 'File cannot be closed because outstanding references exist.' + CR
	#define ERR1190 'File "name" is too large.' + CR
	#define ERR1191 'Cannot save form: an object has an invalid name' + CR
	#define ERR1193 'Missing .RTT section.' + CR
	#define ERR1194 'Link command failed.' + CR
	#define ERR1195 'Object file "file" was compiled in a previous version of FoxPro.' + CR
	#define ERR1196 '"file" is not a Visual FoxPro .EXE file.' + CR
	#define ERR1201 'Too many names used.' + CR
	#define ERR1202 'Program is too large.' + CR
	#define ERR1206 'Recursive macro definition.' + CR
	#define ERR1211 'An IF | ELSE | ENDIF statement is missing.' + CR
	#define ERR1212 'Structure nesting is too deep.' + CR
	#define ERR1213 'There is a missing keyword in the FOR ... ENDFOR or DO CASE ... ENDCASE command structure.' + CR
	#define ERR1214 'ENDTEXT does not have corresponding TEXT statement.' + CR
	#define ERR1217 'Picture error in GET statement.' + CR
	#define ERR1220 'Command contains invalid character.' + CR
	#define ERR1221 'Command is missing required clause.' + CR
	#define ERR1223 'Invalid variable reference.' + CR
	#define ERR1225 'Must be a variable or array.' + CR
	#define ERR1226 'Must be a file variable.' + CR
	#define ERR1229 'Too few arguments.' + CR
	#define ERR1230 'Too many arguments.' + CR
	#define ERR1231 'Missing operand.' + CR
	#define ERR1232 'DIMENSION contains variable declaration without required subscript arguments.' + CR
	#define ERR1234 'Subscript is outside defined range.' + CR
	#define ERR1235 'Structure is invalid.' + CR
	#define ERR1236 'Suspend program before using RESUME.' + CR
	#define ERR1238 'No PARAMETER statement is found.' + CR
	#define ERR1241 'Improper data type in the group expression.' + CR
	#define ERR1242 'Syntax error in the field expression.' + CR
	#define ERR1243 'Internal error: Too many characters in the report.' + CR
	#define ERR1245 'Invalid expression in label definition file.' + CR
	#define ERR1246 'Total label width exceeds allowed size.' + CR
	#define ERR1249 'Too many READ commands are in effect.' + CR
	#define ERR1250 'Too many PROCEDURE commands are in effect.' + CR
	#define ERR1252 'Compiled code for this line is too long.' + CR
	#define ERR1253 'Cannot rename the current directory.' + CR
	#define ERR1254 'Cannot nest key labels.' + CR
	#define ERR1255 'Key label "label" is invalid.' + CR
	#define ERR1256 'Mismatched braces in key label.' + CR
	#define ERR1257 'Key string is too long.' + CR
	#define ERR1258 'Error in the PICTURE clause.' + CR
	#define ERR1294 '"name" is not a valid resource file.' + CR
	#define ERR1296 'Error reading the resource.' + CR
	#define ERR1297 'Command is allowed only in interactive mode.' + CR
	#define ERR1298 '"name" band is too large to fit on page.' + CR
	#define ERR1300 'Function name is missing ).' + CR
	#define ERR1304 'Function name is missing (.' + CR
	#define ERR1306 'Missing comma (,).' + CR
	#define ERR1307 'Cannot divide by 0.' + CR
	#define ERR1308 'Insufficient stack space.' + CR
	#define ERR1309 '"file" is not an object file.' + CR
	#define ERR1310 'Too many characters are specified in the PICTURE clause.' + CR
	#define ERR1313 'Class creation canceled.' + CR
	#define ERR1337 'Cannot nest the PRINTJOB command.' + CR
	#define ERR1338 'File is the wrong version.' + CR
	#define ERR1405 'RUN|! Command failed. "Details".' + CR
	#define ERR1410 'Unable to create temporary work files.' + CR
	#define ERR1411 'RUN|! command string is too long.' + CR
	#define ERR1412 'Cannot locate the COMSPEC environment variable.' + CR
	#define ERR1413 'Page frame cannot be sized that small.' + CR
	#define ERR1420 'OLE object is invalid or corrupted.' + CR
	#define ERR1421 'Cannot activate the OLE server.' + CR
	#define ERR1422 'Error saving the OLE object.' + CR
	#define ERR1423 'Error creating the OLE object.' + CR
	#define ERR1424 'Error copying the OLE object to Clipboard.' + CR
	#define ERR1426 'OLE error code 0x"name".' + CR
	#define ERR1427 'OLE IDispatch exception code "name".' + CR
	#define ERR1428 'OLE IDispatch exception code "number" from "name": "name".' + CR
	#define ERR1429 '"OLE error".' + CR
	#define ERR1431 'Maximum number of OLE arguments is exceeded.' + CR
	#define ERR1434 'Class "name" has not been registered.' + CR
	#define ERR1435 'XML Parse Error' + CR
	#define ERR1436 'Only insertable objects are allowed in General fields.' + CR
	#define ERR1437 'Unable to register the ActiveX control.' + CR
	#define ERR1438 'The ActiveX control module failed to register correctly.' + CR
	#define ERR1439 'Not a ProjectHook class.' + CR
	#define ERR1440 'OLE exception error "name". OLE object may be corrupt.' + CR
	#define ERR1441 'Class cannot be instantiated because member "name" does not exist' + CR
	#define ERR1442 'Class cannot be instantiated because member "name" has wrong # of parameters' + CR
	#define ERR1443 'Interface "name" not found' + CR
	#define ERR1444 'Type Library "name" not found' + CR
	#define ERR1445 'EventHandler object "name" does not IMPLEMENT an interface' + CR
	#define ERR1462 '"name" internal consistency error.' + CR
	#define ERR1463 'No result set has been returned by the server.' + CR
	#define ERR1465 'SQL pass-through internal consistency error.' + CR
	#define ERR1466 'Connection handle is invalid.' + CR
	#define ERR1467 'Property is invalid for local cursors.' + CR
	#define ERR1468 'Property is invalid for table cursors.' + CR
	#define ERR1469 'Property value is out of bounds.' + CR
	#define ERR1470 'Incorrect property name.' + CR
	#define ERR1471 'Incorrect column format.' + CR
	#define ERR1472 'SQL statement parameter is required for non-prepared SqlExec( ) calls.' + CR
	#define ERR1473 'Environment-level property is invalid.' + CR
	#define ERR1474 'Invalid call issued while executing a SQLEXEC( ) sequence.' + CR
	#define ERR1475 'Invalid call issued while executing a SQLMORERESULTS( ) sequence.' + CR
	#define ERR1476 'Invalid call issued while executing a SQLTABLES( ) sequence.' + CR
	#define ERR1477 'Invalid call issued while executing a SQLCOLUMNS( ) sequence.' + CR
	#define ERR1478 'The ChildOrder property of a relation object in the data environment is no longer valid. The relation is being removed.' + CR
	#define ERR1479 'Invalid update column name \"name"\.' + CR
	#define ERR1480 'Warning: The connection sync/async mode cannot be set.' + CR
	#define ERR1481 'Warning: The connection timeout cannot be set.' + CR
	#define ERR1482 'Warning: The query timeout cannot be set.' + CR
	#define ERR1483 'Warning: The connection packet size cannot be set.' + CR
	#define ERR1484 'Warning: The next "cExpr" modified records have already been updated remote.' + CR
	#define ERR1485 'Warning: Invalid data conversion(s) starting at record "name".' + CR
	#define ERR1486 'Warning: Invalid memo field conversions starting at record "name".' + CR
	#define ERR1487 'Warning: The connection transaction mode cannot be set.' + CR
	#define ERR1488 'No connection associated with this cursor' + CR
	#define ERR1489 'General fields cannot be used in the WHERE condition of an update statement. Change the WhereType property of the view.' + CR
	#define ERR1490 'Saving a converted form as a class is not supported.' + CR
	#define ERR1491 'No update tables are specified. Use the Tables property of the Cursor object.' + CR
	#define ERR1492 'No key columns specified for the update table "name". Use the KeyFieldList property of the cursor.' + CR
	#define ERR1493 'SQL parameter is missing.' + CR
	#define ERR1494 'View definition has been changed.' + CR
	#define ERR1495 'Warning: The key defined by the KeyField property for table "alias" is not unique.' + CR
	#define ERR1496 'Warning: No information is available to check remote update conflicts.' + CR
	#define ERR1497 'Connection name is invalid.' + CR
	#define ERR1498 'SQL SELECT statement is invalid.' + CR
	#define ERR1499 'SQL parameter "name" is invalid.' + CR
	#define ERR1501 'Type conversion is not supported for output parameters.' + CR
	#define ERR1502 'Cannot write to the record because it is in use.' + CR
	#define ERR1503 'File cannot be locked.' + CR
	#define ERR1504 'Function not supported for SQL pass-through cursors.' + CR
	#define ERR1507 'Screen code is too large for available memory.' + CR
	#define ERR1508 'Error initializing OLE.' + CR
	#define ERR1509 'Conversion canceled. Adjust the memo BLOCKSIZE.' + CR
	#define ERR1510 'Invalid file format. If this is a dBASE file, it must be converted first. To convert it, type MODIFY LABEL labelfilename.' + CR
	#define ERR1520 'No database is open or set as the current database.' + CR
	#define ERR1521 'This operation not supported for class member objects.' + CR
	#define ERR1522 'Connectivity internal consistency error.' + CR
	#define ERR1523 'Execution was canceled by the user.' + CR
	#define ERR1524 'The selected printer driver does not support direct access.' + CR
	#define ERR1525 'Function is not supported on remote tables.' + CR
	#define ERR1526 'Connectivity error: "name".' + CR
	#define ERR1527 'Cannot locate ODBC library, ODBC32.DLL.' + CR
	#define ERR1528 'ODBC entry point missing, "name".' + CR
	#define ERR1529 'File "name" already exists as part of a database.' + CR
	#define ERR1530 'Fetching canceled; remote table is closed.' + CR
	#define ERR1531 'The table changes cannot be performed as the index or filter expression for index name would be invalid.' + CR
	#define ERR1532 'Type conversion is not supported.' + CR
	#define ERR1533 'This property is read-only.' + CR
	#define ERR1534 'Database "alias" is not open.' + CR
	#define ERR1535 'Cannot close this database because it is being used by a project.' + CR
	#define ERR1536 'Function is not supported on native tables.' + CR
	#define ERR1537 'Cannot add this table: it belongs to database "name".' + CR
	#define ERR1538 'A stored procedure is executing.' + CR
	#define ERR1539 'Trigger failed in "cursor".' + CR
	#define ERR1540 'Session number is invalid.' + CR
	#define ERR1541 'Connection "name" is busy.' + CR
	#define ERR1542 'Base table fields have been changed and no longer match view fields. View field properties cannot be set.' + CR
	#define ERR1543 'Type conversion required by the DataType property for field '"name"'is invalid.' + CR
	#define ERR1544 'DataType property for field '"name"'is invalid.' + CR
	#define ERR1545 'Table buffer for alias "name" contains uncommitted changes.' + CR
	#define ERR1546 'Cannot close table during execution of a table-bound expression.' + CR
	#define ERR1547 'Cannot insert an empty row from a view into its base table(s).' + CR
	#define ERR1548 'Table "alias" has one or more non-structural indexes open. Please close them and retry the Begin Transaction.' + CR
	#define ERR1549 'Data session #number cannot be released with open transaction(s).' + CR
	#define ERR1550 '.DBC internal consistency error.' + CR
	#define ERR1551 'File "name" is an invalid database.' + CR
	#define ERR1552 'File "name" is not a database.' + CR
	#define ERR1553 'File "name" is a database.' + CR
	#define ERR1554 'Error instantiating cursor object. Table "alias" cannot be opened. Object will be ignored.' + CR
	#define ERR1555 'Relational expression is not valid.' + CR
	#define ERR1556 'Table cannot be browsed because cursor object is no longer valid.' + CR
	#define ERR1557 'The database must be opened exclusively.' + CR
	#define ERR1558 'File "name" is not part of a database.' + CR
	#define ERR1559 'Property is not found.' + CR
	#define ERR1560 'Property value is invalid.' + CR
	#define ERR1561 'Database is invalid. Please validate.' + CR
	#define ERR1562'Cannot find object "name" in the database.' + CR
	#define ERR1563 'Cannot find view "name" in the current database.' + CR
	#define ERR1564 'Table "name" already exists in the database.' + CR
	#define ERR1565 'File "name" is part of a database.' + CR
	#define ERR1566 'Cannot issue the PACK command on a database while its objects have open cursors.' + CR
	#define ERR1567 'Primary key property is invalid; please validate database.' + CR
	#define ERR1568 'View fields have been changed. The Update and Key field properties have been reset to the default values.' + CR
	#define ERR1569 'Database "name": File access denied.' + CR
	#define ERR1570 'Database is read-only.' + CR
	#define ERR1571 'The name "name" is already used for another object. Please choose a different name.' + CR
	#define ERR1572 'Cannot delete a database object while it is open in a designer.' + CR
	#define ERR1573 'Cannot change modality of a visible form.' + CR
	#define ERR1574 'Error initializing application object.' + CR
	#define ERR1575 'Object name is invalid.' + CR
	#define ERR1576 'Class "name" is not found in the class library.' + CR
	#define ERR1577 'Table "name" is referenced in a relation.' + CR
	#define ERR1578 'Invalid database table name.' + CR
	#define ERR1579 'Command cannot be issued on a table with cursors in table buffering mode.' + CR
	#define ERR1580 'Feature is not supported for non-.DBC tables.' + CR
	#define ERR1581 'Field "name" does not accept null values.' + CR
	#define ERR1582 'Field "name" validation rule is violated.' + CR
	#define ERR1583 'Record validation rule is violated.' + CR
	#define ERR1584 'Error reading a property from the database. The property is ignored.' + CR
	#define ERR1585 'Update conflict. Use TABLEUPDATE( ) with the lForce parameter to commit the update or TABLEREVERT( ) to roll back the update.' + CR
	#define ERR1586 'Function requires row or table buffering mode.' + CR
	#define ERR1587 'Illegal nested OLDVAL( ) or CURVAL( ).' + CR
	#define ERR1588 'INSERT cannot be issued when row or table buffering is enabled or when integrity constraints are in effect.' + CR
	#define ERR1589 'Table or row buffering requires that SET MULTILOCKS is set to ON.' + CR
	#define ERR1590 'BEGIN TRANSACTION command failed. Nesting level is too deep.' + CR
	#define ERR1591 'END TRANSACTION command cannot be issued without a corresponding BEGIN TRANSACTION command.' + CR
	#define ERR1592 'ROLLBACK command cannot be issued without a corresponding BEGIN TRANSACTION command.' + CR
	#define ERR1593 'Command cannot be issued within a transaction.' + CR
	#define ERR1594 'Illegal to attempt a file lock in a transaction after taking prior record locks.' + CR
	#define ERR1595 'Update conflict. Some of your changes in the current row batch were committed. Use TABLEUPDATE( ) with the lForce parameter to commit the update or the manual transaction to roll back the update.' + CR
	#define ERR1596 'Table buffering is not enabled.' + CR
	#define ERR1597 'Views require either DB_BUFOPTROW or DB_BUFOPTTABLE.' + CR
	#define ERR1598 'Rule and trigger code must balance transaction usage.' + CR
	#define ERR1599 'Data session #number was forced to ROLLBACK all transactions to avoid deadlock.' + CR
	#define ERR1600 'Not enough memory to open a table with the USE command.' + CR
	#define ERR1604 'No menu bar is defined.' + CR
	#define ERR1605'No menu is defined.' + CR
	#define ERR1607 'Maximum menu items allowed (128) is exceeded.' + CR
	#define ERR1608 'Maximum menus allowed (25) is exceeded.' + CR
	#define ERR1609 'Maximum menu item length (50) is exceeded.' + CR
	#define ERR1611 'Menu items and titles must be type Character.' + CR
	#define ERR1612 'No such menu or menu item is defined.' + CR
	#define ERR1621 'No menu titles have been defined for this menu.' + CR
	#define ERR1632 'Window file format is invalid.' + CR
	#define ERR1637 'File must be opened exclusively to convert the Memo file.' + CR
	#define ERR1640 'Access to system Registry denied' + CR
	#define ERR1642 'Color set resource is not found.' + CR
	#define ERR1643 'Printer driver is corrupted.' + CR
	#define ERR1644 'Printer driver is not found.' + CR
	#define ERR1645 'Report contains a nesting error.' + CR
	#define ERR1646 'Total field type must be Date or Numeric.' + CR
	#define ERR1647 'Field expression contains an invalid data type.' + CR
	#define ERR1649 'No previous PRINTJOB command to correspond to this command.' + CR
	#define ERR1651 'CANCEL or SUSPEND is not allowed.' + CR
	#define ERR1652 'Invalid use of a Visual FoxPro function as an array.' + CR
	#define ERR1653 'Label nesting error.' + CR
	#define ERR1657 'Column number must be between 0 and the right margin.' + CR
	#define ERR1659 'The table has memo fields that cannot be converted while open read-only.' + CR
	#define ERR1661 'Microsoft Excel file format is invalid.' + CR
	#define ERR1662 'Lotus 1-2-3 version 1.0 file format is invalid.' + CR
	#define ERR1670 'Multiplan version 4.0 file format is invalid.' + CR
	#define ERR1671 'Cannot import from password-protected file.' + CR
	#define ERR1672 'Cannot append from password protected file.' + CR
	#define ERR1673 'Symphony version 1.0 file format is invalid.' + CR
	#define ERR1674 'Symphony version 1.1 file format is invalid.' + CR
	#define ERR1678 'Lotus 1-2-3 version 3.0 file format is invalid.' + CR
	#define ERR1679 'Import only Worksheet A for Lotus 1-2-3 version 3.0 files.' + CR
	#define ERR1680 'Worksheet A for Lotus 1-2-3 version 3.0 file is hidden.' + CR
	#define ERR1681 'PREVIEW clause is not allowed with OFF/NOCONSOLE or TO PRINT/FILE.' + CR
	#define ERR1682 'Not a user-defined window.' + CR
	#define ERR1683 'Index tag is not found.' + CR
	#define ERR1684 'Index tag or file name must be specified.' + CR
	#define ERR1685 'Project file is invalid.' + CR
	#define ERR1686 'Form file "name" is invalid.' + CR
	#define ERR1687 'Menu file is invalid.' + CR
	#define ERR1688 'Paradox file format is invalid.' + CR
	#define ERR1689 'Cannot build without a main program.' + CR
	#define ERR1690 'Table operation is invalid during indexing.' + CR
	#define ERR1691 'Library file "name" is invalid.' + CR
	#define ERR1693 'Cannot find the menu-generation program.' + CR
	#define ERR1694 'Too many extensions are specified.' + CR
	#define ERR1695 'COLUMN | FORM | ALIAS | NOOVERWRITE | WIDTH are only allowed with the FROM clause.' + CR
	#define ERR1696 'NOWAIT | SAVE | NOENVIRONMENT | IN | WINDOW clauses are not allowed with the FROM clause.' + CR
	#define ERR1698 'COLUMN | ROW | ALIAS | NOOVERWRITE | SIZE | SCREEN are only allowed with the FROM clause.' + CR
	#define ERR1699 'The IN clause is not supported for this window.' + CR
	#define ERR1705 'File access is denied.' + CR
	#define ERR1706 'Cannot sort .IDX files in descending order.' + CR
	#define ERR1707 'Structural .CDX file is not found.' + CR
	#define ERR1708 'File is open in another work area.' + CR
	#define ERR1709 'Database object is being used by someone else.' + CR
	#define ERR1710 'MULTISELECT or MOVER clause is not supported for PROMPT style menus.' + CR
	#define ERR1711 'API library revision mismatch. Rebuild library.' + CR
	#define ERR1712 'Field name is a duplicate or invalid.' + CR
	#define ERR1713 'Field width or number of decimal places is invalid.' + CR
	#define ERR1714 'Window "name" has not been defined.' + CR
	#define ERR1715 'Server "server" is not found.' + CR
	#define ERR1716 'Queue "queue" is not found.' + CR
	#define ERR1717 'Unable to generate a printer driver.' + CR
	#define ERR1718 'File "name" is read-only.' + CR
	#define ERR1719 'Object file "name" is in use and cannot be removed from memory.' + CR
	#define ERR1720 'Cannot issue the SET FORMAT command while a READ command is in progress on a format file.' + CR
	#define ERR1722 'Preprocessor expression is invalid.' + CR
	#define ERR1723 'Mismatched #IF/#ELSIF/#ELSE/#ENDIF.' + CR
	#define ERR1724 'Missing #ENDIF.' + CR
	#define ERR1725 'Constant is already created with #DEFINE.' + CR
	#define ERR1726 'API library is not found.' + CR
	#define ERR1727 'A .DBF-style Help file is required.' + CR
	#define ERR1728 'Color scheme is reserved.' + CR
	#define ERR1730 'Init event failed.' + CR
	#define ERR1731 'Cannot modify a base class.' + CR
	#define ERR1732 'Data type is invalid for this property.' + CR
	#define ERR1733 'Class definition "name" is not found.' + CR
	#define ERR1734 'Property "name" is not found.' + CR
	#define ERR1735 'Error in the class definition. "Details"' + CR
	#define ERR1736 'Error instantiating the object "object".' + CR
	#define ERR1737 '"name" is a method, event, or object.' + CR
	#define ERR1738 'Property "name" is not a method or event.' + CR
	#define ERR1739 'Property setting will not take effect until data environment reloaded.' + CR
	#define ERR1740 '"name" is a read-only property.' + CR
	#define ERR1741 'Cannot add "name". Class definition is cyclical.' + CR
	#define ERR1742 'The data source for this object must be a variable reference.' + CR
	#define ERR1743 'Property "name" is read-only.' + CR
	#define ERR1744 'Object class is invalid for this container.' + CR
	#define ERR1745 '"name" is not a Visual FoxPro event.' + CR
	#define ERR1746 'Class file name for "name" is not valid.' + CR
	#define ERR1747 'Class file "name" is invalid.' + CR
	#define ERR1748 'This file is incompatible with the current version of Visual FoxPro.' + CR
	#define ERR1749 'Form (.SCX) file must contain at least one Form.' + CR
	#define ERR1750 'File was created in a later version of Visual FoxPro than the current version.' + CR
	#define ERR1751 'Class file version is greater than the current version.' + CR
	#define ERR1752 'Class "name" is in use by MODIFY CLASS.' + CR
	#define ERR1753 'Cannot load 32-bit DLL "name".' + CR
	#define ERR1754 'Cannot find entry point "name" in the DLL.' + CR
	#define ERR1755 'Cannot add an object to this class.' + CR
	#define ERR1756 'Member object removed – cannot complete the Save operation.' + CR
	#define ERR1757 'Property "name" is protected.' + CR
	#define ERR1758 'Cannot change property "name" in SetAll method.' + CR
	#define ERR1759 'Expression is invalid. Use a valid expression for "name" property.' + CR
	#define ERR1760 'Member "name" is a class member.' + CR
	#define ERR1761 'Class "name" already exists.' + CR
	#define ERR1762 'Class "name" is not found.' + CR
	#define ERR1763 'Property "name" already exists.' + CR
	#define ERR1764 'Array is not a member of the parent object.' + CR
	#define ERR1765 'Method contains syntax errors. Method is not saved.' + CR
	#define ERR1766 'Object "name" is not found.' + CR
	#define ERR1767 'Parent object will not allow this property setting for "name".' + CR
	#define ERR1768 'Cannot add this object to a Grid.' + CR
	#define ERR1769 'Cannot add this object to a Column.' + CR
	#define ERR1770 'Cannot clear class "class" because it is in use.' + CR
	#define ERR1771 'A member object with this name already exists.' + CR
	#define ERR1772 'You may not change the RecordSource of a BROWSE object.' + CR
	#define ERR1773 'Database object type is invalid.' + CR
	#define ERR1774 'No sheet is found.' + CR
	#define ERR1775 'Worksheet "name" is not found.' + CR
	#define ERR1776 'Class "name" is in use.' + CR
	#define ERR1777 'This command is not supported for views.' + CR
	#define ERR1778 'The table must be converted before appending.' + CR
	#define ERR1779 'Error adding "name" to the object. Duplicate member/property name.' + CR
	#define ERR1780 'This array element has been defined as an object and cannot be redefined in the class definition.' + CR
	#define ERR1781 'An objects control source cannot be set to its Value property.' + CR
	#define ERR1782 'This OLE property cannot be an expression.' + CR
	#define ERR1783 'Invalid class specified for @...Class command.' + CR
	#define ERR1784 'This object is derived from a base class and does not have a parent class.' + CR
	#define ERR1791 'Cannot find the text generation program.' + CR
	#define ERR1792 'Text generation is canceled.' + CR
	#define ERR1793 'The network request is not supported.' + CR
	#define ERR1794 '"name" cannot be enumerated.' + CR
	#define ERR1795 'Cannot arrange an untransported form.' + CR
	#define ERR1796 'No records are found for the current platform.' + CR
	#define ERR1797 'Error occurred in conversion.' + CR
	#define ERR1798 'Cannot find the converter program.' + CR
	#define ERR1799 'Conversion is canceled.' + CR
	#define ERR1800 'SQL: Internal error.' + CR
	#define ERR1801 'SQL: Error correlating fields.' + CR
	#define ERR1802 'SQL: Cannot locate table.' + CR
	#define ERR1803 'SQL: HAVING clause is invalid.' + CR
	#define ERR1804 'SQL: Statement is invalid.' + CR
	#define ERR1805 'SQL: Too many subqueries.' + CR
	#define ERR1806 'SQL: Column "field | variable" is not found.' + CR
	#define ERR1807 'SQL: GROUP BY clause is invalid.' + CR
	#define ERR1808 'SQL: ORDER BY clause is invalid.' + CR
	#define ERR1809 'SQL: Out of memory.' + CR
	#define ERR1810 'SQL: Invalid use of subquery.' + CR
	#define ERR1811 'SQL: Aggregate on non-numeric expression.' + CR
	#define ERR1812 'SQL: Statement too long.' + CR
	#define ERR1813 'SQL: Use of UNION in subquery is invalid.' + CR
	#define ERR1814 'SQL: Queries of this type are not supported.' + CR
	#define ERR1815 '"cursor" must be created with SELECT ... INTO TABLE.' + CR
	#define ERR1818 'SQL: FROM clause is required.' + CR
	#define ERR1819 'SQL: DISTINCT is invalid.' + CR
	#define ERR1820 'SQL: SELECT contains invalid *.' + CR
	#define ERR1822 'SQL: Invalid aggregate field.' + CR
	#define ERR1825 'SQL: Subquery is invalid.' + CR
	#define ERR1826 'SQL: SELECT is invalid.' + CR
	#define ERR1828 'SQL: Illegal GROUP BY in subquery.' + CR
	#define ERR1830 'SQL: Index is not found.' + CR
	#define ERR1831 'SQL: Error building temporary index.' + CR
	#define ERR1832 '"field | variable" is not unique and must be qualified.' + CR
	#define ERR1833 'SQL: WHERE clause is invalid.' + CR
	#define ERR1834 'SQL: Too many UNIONs.' + CR
	#define ERR1839 'SQL: Operation was canceled.' + CR
	#define ERR1841 'SQL: Too many columns referenced.' + CR
	#define ERR1842 'SQL: Subquery nesting is too deep.' + CR
	#define ERR1844 'Cannot nest aggregate functions.' + CR
	#define ERR1845 'SQL expression is too complex.' + CR
	#define ERR1846 'Cannot GROUP by aggregate field.' + CR
	#define ERR1851 'SELECTs are not UNION compatible. "Details"' + CR
	#define ERR1860 'Subquery returned more than one record.' + CR
	#define ERR1864 'SQL: Too many fields in UPDATE.' + CR
	#define ERR1865 'SQL: Invalid SET expression in UPDATE.' + CR
	#define ERR1866 'SQL: Invalid TOP specification.' + CR
	#define ERR1867 'SQL: TOP requires an ORDER BY.' + CR
	#define ERR1870 'ALTER TABLE operation interrupted.' + CR
	#define ERR1871 'Cannot DROP all existing columns.' + CR
	#define ERR1872 'Too many columns.' + CR
	#define ERR1875 'Multiple warnings occurred performing the requested index modifications.' + CR
	#define ERR1877 'No rule to DROP.' + CR
	#define ERR1878 'No default value to DROP.' + CR
	#define ERR1879 'No primary key.' + CR
	#define ERR1880 'Related table is not found in current database.' + CR
	#define ERR1881 'Error loading file - record number n. "object" <or one of its members>. "Issue": "error".' + CR
	#define ERR1882 'Related tag is not found or not primary or candidate.' + CR
	#define ERR1883 'Primary key already exists.' + CR
	#define ERR1884 'Uniqueness of index "name" is violated.' + CR
	#define ERR1885 'Only structural tags can be defined as candidate.' + CR
	#define ERR1886 'Index does not accept NULL.' + CR
	#define ERR1887 'Illegal recursion in rule evaluation.' + CR
	#define ERR1888 'Tag name is too long.' + CR
	#define ERR1889 'A table in multiple relationships can only have one child order.' + CR
	#define ERR1890 'SQL: Cannot determine data type of SQL column "column".' + CR
	#define ERR1903 'String is too long to fit.' + CR
	#define ERR1907 'Drive specifier is invalid.' + CR
	#define ERR1908 'Length or decimal place argument is invalid.' + CR
	#define ERR1909 'Cannot update project from project metafile.' + CR
	#define ERR1910 'Illegal printer driver recursion.' + CR
	#define ERR1911 'Localized product is required for this environment.' + CR
	#define ERR1912 'Operation is invalid for a General field.' + CR
	#define ERR1913 'Field must be a General field.' + CR
	#define ERR1914 'Code page number is invalid.' + CR
	#define ERR1915 'Collating sequence "name" is not found.' + CR
	#define ERR1916 'To use this feature, set CODEPAGE=AUTO in your CONFIG.FPW file and restart Visual FoxPro.' + CR
	#define ERR1917 'Script error: "name".' + CR
	#define ERR1918 'File name is too long.' + CR
	#define ERR1919 'Objects cannot be programmatically deleted from the Class Designer.' + CR
	#define ERR1922 'Volume does not exist.' + CR
	#define ERR1923 'Object "name" is not found.' + CR
	#define ERR1924 '"name" is not an object.' + CR
	#define ERR1925 'Unknown member "name".' + CR
	#define ERR1926 'Cannot nest class definitions.' + CR
	#define ERR1927 'Statement is not valid in a class definition.' + CR
	#define ERR1928 'Statement is only valid within a class definition.' + CR
	#define ERR1929 '"name" can only be used within a method.' + CR
	#define ERR1930 'Cannot redefine "name".' + CR
	#define ERR1931 'Statement is not in a procedure.' + CR
	#define ERR1932 '"name" cannot be closed while suspended.' + CR
	#define ERR1933 'File "name" is not closed.' + CR
	#define ERR1934 'Statement only valid within a method.' + CR
	#define ERR1935 'The current object does not inherit from class "name".' + CR
	#define ERR1936 'Application object not initialized.' + CR
	#define ERR1937 'Procedure file "name" is not found.' + CR
	#define ERR1938 'Object is not contained in a "name".' + CR
	#define ERR1939 'WITH/ENDWITH mismatch.' + CR
	#define ERR1940 'Expression is not valid outside of WITH/ENDWITH.' + CR
	#define ERR1941 'Error code is not valid.' + CR
	#define ERR1942 'Objects cannot be assigned to arrays.' + CR
	#define ERR1943 'Member "name" does not evaluate to an object.' + CR
	#define ERR1944 'Cannot find the builder program.' + CR
	#define ERR1945 'The current object has been released.' + CR
	#define ERR1946 'Project file "name" is in the wrong version.' + CR
	#define ERR1947 'Expression is too complex.' + CR
	#define ERR1948 'Cannot modify a class that is in use.' + CR
	#define ERR1949 'Class name is invalid.' + CR
	#define ERR1950 'Class definition "name" is recursive.' + CR
	#define ERR1951 'Cannot clear the object "object" because it is in use.' + CR
	#define ERR1952 'Cannot base a view on itself.' + CR
	#define ERR1953 'Feature is only available if the object is in design mode.' + CR
	#define ERR1954 'The builder program is already running.' + CR
	#define ERR1955 'WIN.INI/registry is corrupted.' + CR
	#define ERR1956 'Printer access denied.' + CR
	#define ERR1957 'Error accessing printer spooler.' + CR
	#define ERR1958 'Error loading printer driver.' + CR
	#define ERR1959 'Invalid coordinates.' + CR
	#define ERR1960 'Illegal redefinition of variable "name".' + CR
	#define ERR1961 'A subdirectory or file "name" already exists.' + CR
	#define ERR1962 'The directory is not empty.' + CR
	#define ERR1963 'Directory is not found.' + CR
	#define ERR1964 'No PageFrame or Page is found in FormSet or Form with WindowType set to READ or READ MODAL.' + CR
	#define ERR1965 'One of the members of this class is based on a nonvisual class. Cannot write .VCX file.' + CR
	#define ERR1966 'Data environment is already loaded.' + CR
	#define ERR1967 'Data environment is already unloaded.' + CR
	#define ERR1968 'One of the members of this Form or FormSet is based on a nonvisual class. Cannot write .SCX file.' + CR
	#define ERR1969 'The clipboard contained one or more objects that could not be added to the container. Those objects were not pasted.' + CR
	#define ERR1970 'Cannot reopen project file "name".' + CR
	#define ERR1971 'Cannot compile until the current COMPILE command has completed.' + CR
	#define ERR1972 'Array "name" is in use.' + CR
	#define ERR1973 'Error creating table: "name".' + CR
	#define ERR1974 'Arrays cannot be assigned to array elements.' + CR
	#define ERR1975 'Member object "name" has not been instantiated.' + CR
	#define ERR1976 'Cannot resolve backlink.' + CR
	#define ERR1977 'Exclusive open required to update this file. Please reopen.' + CR
	#define ERR1978 'Cannot visually modify a class of this type.' + CR
	#define ERR1979 'Cannot visually modify a class based on a nonvisual class.' + CR
	#define ERR1981 'Compile error in file "name".' + CR
	#define ERR1982 'The TO clause can only be used with modal Forms and FormSets.' + CR
	#define ERR1983 '"name" objects cannot return a value.' + CR
	#define ERR1984 'The fields in table '"name"'did not match the entries in the database.' + CR
	#define ERR1985 'Object already has a data environment; cannot use another one with the SaveAs method.' + CR
	#define ERR1986 'GDI memory is low, close one or more windows and try again.' + CR
	#define ERR1987 'Objects cannot be programmatically added to the Form Designer's FormSet.' + CR
	#define ERR1988 'Currency value is out of range.' + CR
	#define ERR1989 'Objects cannot be programmatically deleted from the Form Designer.' + CR
	#define ERR1991 'Form file "name" is from a previous version of FoxPro. It must be converted to the current format before it can be executed.' + CR
	#define ERR1992 '"name" is not a function, procedure or program.' + CR
	#define ERR1993 'Class library file "name" is not found.' + CR
	#define ERR1994 'Include file "name" is not found.' + CR
	#define ERR1995 'Error loading the data environment. Table is in use.' + CR
	#define ERR1996 'The validation rule for field "name" does not evaluate to a logical or NULL type.' + CR
	#define ERR1997 'The default value for field "name" does not evaluate to the correct type for the field.' + CR
	#define ERR1998 'The index expression for index "name" contains an invalid reference to a Memo, General, or Picture field.' + CR
	#define ERR1999 'Function is not implemented.' + CR
	#define ERR2000 'Memory is low, so streaming output updating has been disabled.' + CR
	#define ERR2001 'The name of the object file for "file" is already used by another program in the project.' + CR
	#define ERR2002 'Cannot build a DLL without OLE public classes.' + CR
	#define ERR2003 'OLE Changed Properties stream is the wrong version. Subclassed properties ignored.' + CR
	#define ERR2004 'The table file "name" has moved. Please validate database "name" and try again.' + CR
	#define ERR2005 'Error with "name" - "property": "error".' + CR
	#define ERR2006 'Cannot locate your Web browser.' + CR
	#define ERR2007 'Invalid operation for offline view while offline.' + CR
	#define ERR2008 'Invalid operation for offline view while being used online.' + CR
	#define ERR2009 'Object is not an offline view.' + CR
	#define ERR2010 'Offline views must be used exclusively when being used online.' + CR
	#define ERR2011 'Invalid operation for offline view.' + CR
	#define ERR2012 'Cannot call SetFocus from within a When, Valid, RangeHigh or RangeLow event.' + CR
	#define ERR2013 'Cannot open persistent table buffer directly.' + CR
	#define ERR2014 'Fields marked as update keys will be cleared.' + CR
	#define ERR2015 'Offline view must be used online for this command' + CR
	#define ERR2016 'Removing a class member is not allowed.' + CR
	#define ERR2017 'Cannot reuse offline view in different mode.' + CR
	#define ERR2018 'Reconnect of offline view failed.' + CR
	#define ERR2019 'Cannot create offline view on a currently modified view.' + CR
	#define ERR2020 'The class file associated with this field cannot be found – class association cleared.' + CR
	#define ERR2021 'The DataObject cannot be modified in the OLEDragOver or OLEDragDrop event.' + CR
	#define ERR2022 'The specified file or path was not found.' + CR
	#define ERR2023 'There is no application associated with the given filename extension.' + CR
	#define ERR2024 'A sharing violation occurred.' + CR
	#define ERR2025 'The SQL Statement is too complex for the View/Query Designer.' + CR
	#define ERR2026 'Invalid locale ID.' + CR
	#define ERR2027 'Declare DLL call caused an exception.' + CR
	#define ERR2028 'API call caused an exception.' + CR
	#define ERR2029 'Class "name" is not a Form class.' + CR
	#define ERR2030 'Cannot delete file "name".' + CR
	#define ERR2031 'User-interface operation not allowed at this time.' + CR
	#define ERR2032 'Ambiguous date/datetime constant.' + CR
	#define ERR2033 'CTOD and CTOT can produce incorrect results.' + CR
	#define ERR2034 'Date/datetime evaluated to an invalid value.' + CR
	#define ERR2035 'Date/datetime contains illegal characters.' + CR
	#define ERR2036 'The current Help file is empty.' + CR
	#define ERR2038 'Microsoft Visual FoxPro doesn't support and cannot open this format of recordset.' + CR
	#define ERR2039 'Failed to create recordset.' + CR
	#define ERR2040 'Field mismatch.' + CR
	#define ERR2041 'Recordset does not exist.' + CR
	#define ERR2042 'Foxcode table not found, is not correct version or is incompatible.' + CR
	#define ERR2043 'Foxcode script "name" failure.' + CR
	#define ERR2044 'Textmerge is recursive.' + CR
	#define ERR2045 'Cannot set DBCEventFile property when DBCEvents is off.' + CR
	#define ERR2046 'Foxtask table is corrupted or not the correct version.' + CR
	#define ERR2047 'Invalid character entered.' + CR
	#define ERR2048 'Invalid COMATTRIB value for "name".' + CR
	#define ERR2049 'Error loading HtmlHelp 2.0 collection.' + CR
	#define ERR2050 'Help for this topic/context not implemented.' + CR
	#define ERR2051 'Menu item's conditional statement is too long.' + CR
	#define ERR2052 'OrderBy clause is too long.' + CR
	#define ERR2053 'GroupBy clause is too long.' + CR
	#define ERR2054 'Cannot release object.' + CR
	#define ERR2055 'Query Parse Error - Try rebuilding in Query Wizard or by using View Designer Join Tab.' + CR
	#define ERR2056 'The specified member class does not exist or is of wrong type.' + CR
	#define ERR2057 'The specified class library does not exist or does not contain a valid member class.' + CR
	#define ERR2058 'TRY/CATCH/FINALLY/ENDTRY mismatch or error.' + CR
	#define ERR2059 'Unhandled Structured Exception.' + CR
	#define ERR2060 'RETURN/RETRY statement not allowed in TRY/CATCH.' + CR
	#define ERR2061 'Index or expression does not match an existing member of the collection.' + CR
	#define ERR2062 'The specified Key already exists.' + CR
	#define ERR2063 'A Key must be specified when adding an item to this collection.' + CR
	#define ERR2064 'A Key cannot be specified when adding an item to this collection.' + CR
	#define ERR2065 'Table "name" has a file length / record number inconsistency.' + CR
	#define ERR2066 'Index file "file" is corrupted. Please rebuild it.' + CR
	#define ERR2067 'Cursor "name" does not have a valid table or view reference.' + CR
	#define ERR2068 'Data environment "name" does not contain a cursor object.' + CR
	#define ERR2069 'Forms or Form classes that specify a DEClass and DEClassLibrary cannot be converted to or used with a FormSet.' + CR
	#define ERR2070 'Cannot assign a class value to this member.' + CR
	#define ERR2071 'User Thrown Error.' + CR
	#define ERR2072 'Cursor cannot be modified because it contains an unsaved.' + CR
	#define ERR2073 'Cannot change MemberClass because existing member objects have outstanding references.' + CR
	#define ERR2074 'Result is incompatible with cursor schema.' + CR
	#define ERR2075 'CursorSchema property is not specified.' + CR
	#define ERR2076 'Operation is not allowed for CursorAdapter.' + CR
	#define ERR2077 'Operation is not allowed for CursorAdapter at this time.' + CR
	#define ERR2078 'CursorAdapter "name" cannot be loaded for design.' + CR
	#define ERR2079 'Cannot close or detach extended cursor because it is currently in design mode.' + CR
	#define ERR2080 'ADODB.Recordset is already opened.' + CR
	#define ERR2081 'ADODB.Command is already opened.' + CR
	#define ERR2082 'Cannot update ADODB.Recordset while cursor, created by CursorAdapter.CursorFill method, is not attached to a CursorAdapter object.' + CR
	#define ERR2083 'Cannot update ADODB.Recordset because it is read-only.' + CR
	#define ERR2084 'Cannot update ADODB.Recordset because it does not support a Bookmark property.' + CR
	#define ERR2085 'Cannot update ADODB.Recordset because FOX cursor does not have an ADOBookmark column.' + CR
	#define ERR2086 'DEClass cannot be loaded.' + CR
	#define ERR2087 'Window "name" is not a dockable window. (Error 2087)' + CR
	#define ERR2088 'Field "name" is read-only.' + CR
	#define ERR2089 'The "name" event has failed.' + CR
	#define ERR2090 'CursorAdapter does not have an associated cursor.' + CR
	#define ERR2091 'Table "name" has become corrupted. The table will need to be repaired before using again.' + CR
	#define ERR2092 'CursorAdapter cannot locate current record in the buffer. The record may have been reverted.' + CR
	#define ERR2093 'Syntax error: "name" is not allowed in the view script or is in the wrong place.' + CR
	#define ERR2094 'XML Schema is too complex.' + CR
	#define ERR2095 'XMLTable object does not have associated XMLAdapter object.' + CR
	#define ERR2096 'XML document is not loaded.' + CR
	#define ERR2097 'XMLTable object does not have associated fields.' + CR
	#define ERR2098 'Invalid element in XMLTable.Fields collection.' + CR
	#define ERR2099 'Value of XMLTable.XMLName must be used as key value for collection.' + CR
	#define ERR2100 'Value of XMLField.XMLName must be used as key value for collection.' + CR
	#define ERR2101 'Unable to attach object with empty XMLName property.' + CR
	#define ERR2102 'Unable to change XMLName property while XMLTable object belongs to XMLAdapter object.' + CR
	#define ERR2103 'Unable to change XMLName property while XMLField object belongs to XMLTable object.' + CR
	#define ERR2104 'There is a duplicate table "name" in XML schema.' + CR
	#define ERR2105 'There is a duplicate field "name" in XML schema.' + CR
	#define ERR2107 'XMLAdapter.ToXML cannot be called while there is a loaded XML document.' + CR
	#define ERR2108 'XMLTable.Alias is empty.' + CR
	#define ERR2109 'XMLTable has child table.' + CR
	#define ERR2110 'XML Error: "error"' + CR
	#define ERR2112 'Cursor "name" is attached to another CursorAdapter object.' + CR
	#define ERR2116 'This feature requires MSXML4 SP1 or later.' + CR
	#define ERR2118 'XMLAdapter: fractionDigits must not be greater than or equal to maxLength.' + CR
	#define ERR2120 'Unable to infer XML schema.' + CR
	#define ERR2121 'Unable to open offline view in ADMIN/ONLINE mode inside a transaction.' + CR
	#define ERR2122 'Unable to close offline view in ADMIN/ONLINE mode inside a transaction.' + CR
	#define ERR2123 'Unable to set external schema location when inline schema is used.' + CR
	#define ERR2124 'XML document does not have a root element.' + CR
	#define ERR2125 'CursorAdapter and XMLTable objects do not belong to the same data session.' + CR
	#define ERR2126 'XML document is not a DiffGram.' + CR
	#define ERR2127 'XMLAdapter.XMLName is empty.' + CR
	#define ERR2128 'XML node does not belong to MSXML4.DOMDocument.' + CR
	#define ERR2129 'XMLAdapter object doesn't have associated tables.' + CR
	#define ERR2130 'XMLTable object with XMLName "name" does not have associated fields.' + CR
	#define ERR2131 'TEXT does not have corresponding ENDTEXT statement' + CR
	#define ERR2132 'XMLTable object already has parent or is associated with XMLAdapter object.' + CR
	#define ERR2133 'Unable to emit XML, two or more cursors use different code pages.' + CR
	#define ERR2134 'Value of XMLName, XMLNamespace or XMLPrefix property should be a Unicode string.' + CR
	#define ERR2135 'Conversion to Unicode has failed.' + CR
	#define ERR2136 'Conversion from Unicode has failed.' + CR
	#define ERR2137 'Vfp.VFPXMLProgId doesn't support cSchemaLocation parameter for XMLUpdateGram().' + CR
	#define ERR2138 'CursorAdapter is unable to determine DataSourceType for the operation.' + CR
	#define ERR2139 'SelectCmd is empty.' + CR
	#define ERR2140 'Both Unicode and IsBinary properties can not be set to .T..' + CR
	#define ERR2141 'Field size for Unicode value can not be odd number.' + CR
	#define ERR2142 'Field for Unicode value should not use code page translation.' + CR
	#define ERR2143 'ADODB.Recordset is not opened.' + CR
	#define ERR2144 'XMLField object is already associated with XMLTable object.' + CR
	#define ERR2145 'Property "name" has invalid value.' + CR
	#define ERR2146 'Invalid key column name "name".' + CR
	#define ERR2147 'Calling OpenTables or CloseTables is not allowed while either of those methods are in the process of executing.' + CR
	#define ERR2148 'SQL: The ORDER BY clause is invalid in subqueries, unless TOP is also specified' + CR
	#define ERR2149 'SQL: Invalid SET expression in UPDATE, "table name" is not a target table' + CR
	#define ERR2150 'SQL: Table for UPDATE or DELETE cannot be outer joined' + CR
	#define ERR2151 'SQL: Cannot UPDATE or DELETE from subquery' + CR
	#define ERR2152 'The Dockable property cannot be enabled possibly due to conflicting properties' + CR
	#define ERR2153 'Invalid collate sequence' + CR
	#define ERR2154 'Unknown member object "object name"' + CR
	#define ERR2155 'Number of affected rows is not available' + CR
	#define ERR2156 'Invalid index expression for a Binary index' + CR
	#define ERR2157 'Filter expression is not allowed for a Binary index' + CR
	#define ERR2158 'Unable to locate target record in ADODB.Recordset' + CR
	#define ERR2159 'Unable to cast NULL value to a NOT NULL data type' + CR
	#define ERR2160 'Invalid timestamp column name "column name"' + CR
	#define ERR2161 'Invalid Insert refresh column name "column name"' + CR
	#define ERR2162 'Invalid Insert refresh key column name "column name"' + CR
	#define ERR2163 'Invalid Update refresh column name "column name"' + CR
	#define ERR2164 'Invalid Update refresh key column name "column name"' + CR
	#define ERR2165 'The refresh key defined for table "table name" is not unique' + CR
	#define ERR2166 'The refresh key defined for table "table name" is not found' + CR
	#define ERR2167 'Source field for refresh is not found' + CR
	#define ERR2168 'Invalid data source type for RecordRefresh operation' + CR
	#define ERR2169 'Cannot refresh record from ADODB.Recordset because it does not support a Bookmark property' + CR
	#define ERR2170 'Cannot refresh record from ADODB.Recordset because FOX cursor does not have an ADOBookmark column' + CR
	#define ERR2171 'Invalid refresh ignore column name "column name"' + CR
	#define ERR2172 'Field "field name" is not fetched' + CR
	#define ERR2173 'Cursor "cursor name" is in use and cannot be closed' + CR
	#define ERR2174 'Field "field name" is not associated with a base table' + CR
	#define ERR2175 'CursorAdapter internal error' + CR
	#define ERR2176 'Connection "connection name" is in manual commit mode' + CR
	#define ERR2177 'Inner and outer XMLTable objects are not associated with the same XMLAdapter object' + CR
	#define ERR2178 'There is no relation to the nested table "table name".' + CR
	#define ERR2179 'Nested XML format is incompatible with 'Changes Only' + CR
	#define ERR2180 'XMLAdapter XMLName property is an XPath expression' + CR
	#define ERR2181 'XMLTable XMLName property is an XPath expression' + CR
	#define ERR2182 'XMLName property contains illegal symbol(s)' + CR
	#define ERR2183 'Operation requires that SET MULTILOCKS is set to ON' + CR
	#define ERR2184 'Code page for the field "field name" doesn't match cursor's code page' + CR
	#define ERR2185 'Unable to infer cursor's code page from XML document' + CR
	#define ERR2186 'Error building sort key' + CR
	#define ERR2187 'Recursive XMLTable nesting is not allowed' + CR
	#define ERR2188 'Cursor doesn´t support ADOBookmark property' + CR
	#define ERR2189 'SQL: Too many fields in final or intermediate result have the same name' + CR
	#define ERR2190 'FontCharSet number is invalid' + CR
	#define ERR2191 'File is in use in another data session' + CR
	#define ERR2192 'Illegal operation for a table with pending changes' + CR
	#define ERR2193 'Illegal operation in rule evaluation' + CR
	#define ERR2194 'Output page "page" is not available' + CR
	#define ERR2195 'The cursor is already associated with a record set' + CR
	#define ERR2196 'Only single SQL SELECT statement can be enclosed in parenthesis' + CR
	#define ERR2197 'Property "property name" value is too long' + CR
	#define ERR2198 'Index tag is not found for Cursor object "cursor name"' + CR
	#define ERR2199 'Error building key for index "name".' + CR
	#define ERR2200 'Index "name" is in use and cannot be closed' + CR
	#define ERR2201 'Cannot determine data type of the expression' + CR
#ENDIF